install.packages(c("docopt", "BiocManager"), repos='https://stat.ethz.ch/CRAN/')
BiocManager::install(c("graph", "RBGL", "ggm", "Rgraphviz"), quiet=TRUE, update=TRUE, ask=FALSE)
install.packages(c("MASS", "momentchi2", "pcalg", "kpcalg"), dependencies=TRUE, quiet=TRUE, repos='https://stat.ethz.ch/CRAN/')
install.packages("remotes", dependencies=TRUE, repos='https://stat.ethz.ch/CRAN/')
library(remotes)
install_github("Diviyan-Kalainathan/RCIT")
install.packages("./R_archives/SID_1.0.tar.gz", repos=NULL, type="source")
install.packages(c("glmnet", "boost", "mboost"), dependencies=TRUE, quiet=TRUE, repos='https://stat.ethz.ch/CRAN/')
install.packages("./R_archives/CAM_1.0.tar.gz", repos=NULL, type="source")