from setuptools import setup, find_packages
setup(
    name='avici',
    version='1.0.0',
    description='Amortized Inference for Causal Structure Learning',
    author='Lars Lorch',
    author_email='lars.lorch@inf.ethz.ch',
    url="https://github.com/larslorch/avici",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    packages=find_packages(),
    install_requires=[
        'jax>=0.3.17',
        'jaxlib>=0.3.14',
        'imageio==2.9.0',
        'jupyter==1.0.0',
        'matplotlib==3.3.3',
        'numpy==1.23.4',
        'scipy==1.9.2',
        'pandas==1.1.4',
        'igraph==0.9.8',
        'python-igraph==0.9.8',
        'scikit-learn==1.0.2',
        'sklearn==0.0',
        'tqdm==4.64.1',
        'dm-haiku==0.0.8',
        'psutil==5.9.2',
        'optax==0.1.3',
        'pyarrow==7.0.0',
        'tensorflow-datasets~=4.3.0',
        'deepdiff==5.8.1',
        'seaborn==0.12.0',
        'torch==1.11.0',
        'causaldag==0.1a163',
    ]
)
