---
train_n_vars: [5]
test_n_vars: [7]
test_n_datasets: 5
data:
  train:
    - n_observations_obs: 44
      n_observations_int: 33

      g:
        - __func__: scale_free
          edges_per_var: [ 2 ]
          power: [ 1.0 ]

      mechanism:
        - __func__: linear_additive

          param:
            - __func__: signed_uniform
              low: 0.25
              high: 3.0
              
          bias:
            - __func__: uniform
              low: -3.0
              high: 3.0
              
          noise:
            - __func__: gaussian

          noise_scale:
            - __func__: uniform
              low: 0.2
              high: 2.0

          n_interv_vars: -1
          interv_dist:
            - __func__: signed_uniform
              low:  1.0
              high: 5.0


  test:train-mix:
    - n_observations_obs: 44
      n_observations_int: 33

      g:
        - __func__: scale_free
          edges_per_var: [ 2 ]
          power: [ 1.0 ]

      mechanism:
        - __func__: linear_additive

          param:
            - __func__: signed_uniform
              low: 0.25
              high: 3.0

          bias:
            - __func__: uniform
              low: -3.0
              high: 3.0
              
          noise:
            - __func__: laplace

          noise_scale_heteroscedastic:
            - rff:
              length_scale: 10.0
              output_scale: 2.0

          n_interv_vars: -1
          interv_dist:
            - __func__: signed_uniform
              low:  1.0
              high: 5.0