---
train_n_vars: [5]
test_n_vars: [7]
test_n_datasets: 5
data:
  train:
    - n_observations_obs: 44
      n_observations_int: 33

      g:
        - __func__: scale_free_inv
          edges_per_var: [ 1, 2, 3 ]
          power: [0.5, 0.8, 1.0, 1.2, 1.5]
        - __func__: erdos_renyi
          edges_per_var: [ 1.0, 1.5, 2.0, 2.5 ]

      mechanism:
        - __func__: kosergio_noisy_count
          tech_noise_config: [ 10x-chromium ]
          cell_types:
            __func__: randint
            low:  5
            high: 5
          decays: [ 0.7, 0.8, 0.9 ]
          noise_params: [ 0.9, 1.0, 1.1 ]
          b:
            - __func__: uniform
              low: 0.5
              high: 2.0
          k_param:
            - __func__: uniform
              low: 1.0
              high: 5.0
          k_sign_p:
            - __func__: beta
              a: 1.0
              b: 1.0
            - __func__: beta
              a: 0.5
              b: 0.5
          hill: [ 1.9, 2.0, 2.1 ]

          n_ko_genes: -1

  test:ood:
    - n_observations_obs: 44
      n_observations_int: 33

      g:
        - __func__: ecoli
          topk: 0.2

        - __func__: yeast
          topk: 0.2

      mechanism:
        - __func__: kosergio_noisy_count
          tech_noise_config: [ illumina, drop-seq, smart-seq ]

          cell_types:
            __func__: randint
            low: 10
            high: 10
          decays: [ 0.5, 1.5 ]
          noise_params: [ 0.5, 1.5 ]
          b:
            - __func__: uniform
              low: 2
              high: 4
          k_param:
            - __func__: uniform
              low: 1.0
              high: 3.0
            - __func__: uniform
              low: 3.0
              high: 7.0
          k_sign_p:
            - __func__: beta
              a: 0.2588
              b: 0.2499
          hill: [ 1.5, 2.5 ]

          n_ko_genes: -1
