---
train_n_vars: [2, 5, 10, 20, 30, 40, 50]
test_n_vars: [30, 100]
test_n_datasets: 30
data:
  - n_observations_obs: 600
    n_observations_int: 200

    graph:
      - __class__: ScaleFreeTranspose
        edges_per_var: [ 1, 2, 3 ]
        power: [0.5, 0.8, 1.0, 1.2, 1.5]
      - __class__: ErdosRenyi
        edges_per_var: [ 1.0, 2.0, 3.0 ]

    mechanism:
      - __class__: GRNSergio
        add_outlier_effect: true
        add_lib_size_effect: true
        add_dropout_effect: true
        return_count_data: true

        tech_noise_config: [ 10x-chromium ]
        cell_types:
          __class__: RandInt
          low:  5
          high: 5
        decays: [ 0.7, 0.8, 0.9 ]
        noise_params: [ 0.9, 1.0, 1.1 ]
        b:
          - __class__: Uniform
            low: 1.0
            high: 3.0
        k_param:
          - __class__: Uniform
            low: 1.0
            high: 5.0
        k_sign_p:
          - __class__: Beta
            a: 1.0
            b: 1.0
          - __class__: Beta
            a: 0.5
            b: 0.5
        hill: [ 1.9, 2.0, 2.1 ]

        n_ko_genes: -1
